# Generated by Django 5.1.6 on 2025-02-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='supplied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
        ),
    ]
