# Generated by Django 5.1.6 on 2025-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_alter_waterbottle_supplied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='current_qty',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='mouth_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
